### ISSUE TITLE
 Get post info 

### ISSUE THREAD

**Issue by 89z** [Quatrecentquatre-404/instagram-guest-api#2]
If I have a post such as this:

https://www.instagram.com/p/CT-cnxGhvvO/

How do I get the info for this post? Sorry for the basic question, but I have looked over the API and am not seeing a way to do this.

**Comment by 89z** [comment]
I think this does it:

~~~
from src import Instagram

def main():
   post = Instagram.fetch_post_properties('CT-cnxGhvvO')
   print(post)

if __name__ == "__main__":
    main()
~~~

but I get an error:

~~~
Traceback (most recent call last):
  File "D:\Desktop\instagram-guest-api-main\src\util.py", line 26, in handle_json
    data = json.loads(request["text"])
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Desktop\instagram-guest-api-main\tests.py", line 16, in <module>
    main()
  File "D:\Desktop\instagram-guest-api-main\tests.py", line 6, in main
    post = Instagram.fetch_post_properties('CT-cnxGhvvO')
  File "D:\Desktop\instagram-guest-api-main\src\core.py", line 128, in fetch_post_properties
    data = handle_json(request)
  File "D:\Desktop\instagram-guest-api-main\src\util.py", line 31, in handle_json
    raise LoginRedirectionError(
src.exceptions.LoginRedirectionError: You are being redirected to the login
page. Please, create an issue and describe what happened at
https://github.com/Quatrecentquatre-404/instagram-guest-api/issues/new.
~~~

**Comment by Quatrecentquatre-404** [comment]
Hi,
thanks again for opening an issue, I appreciate getting all details.
I'm going to investigate. 😄

**Comment by Quatrecentquatre-404** [comment]
So, I've forgot to declare a class method as static, so I pushed the new version. You can try this snippet :
```python
from src import Instagram

def main():
    api = Instagram()
    post = api.fetch_post_properties("CT-cnxGhvvO")
    # Outputs something of type types/posts/post_properties.json
    print(post)

if __name__ == "__main__":
    main()
```

You should see the expected output.
I hope this helped, let me know.

**Comment by 89z** [comment]
Thank you for update. However I still get error:


~~~
Traceback (most recent call last):
  File "D:\Desktop\instagram-guest-api-main\src\util.py", line 26, in handle_json
    data = json.loads(request["text"])
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Desktop\instagram-guest-api-main\tests.py", line 10, in <module>
    main()
  File "D:\Desktop\instagram-guest-api-main\tests.py", line 5, in main
    post = api.fetch_post_properties("CT-cnxGhvvO")
  File "D:\Desktop\instagram-guest-api-main\src\core.py", line 128, in fetch_post_properties
    data = handle_json(request)
  File "D:\Desktop\instagram-guest-api-main\src\util.py", line 31, in handle_json
    raise LoginRedirectionError(
src.exceptions.LoginRedirectionError: You are being redirected to the login
page. Please, create an issue and describe what happened at
https://github.com/Quatrecentquatre-404/instagram-guest-api/issues/new.
~~~

**Comment by Quatrecentquatre-404** [comment]
Alright, so, this time it doesn't seems to be a code bug, but an Instagram ratelimit. What you can do is connect to you Instagram account, go on the Network tab from the Developper console, and then get your Instagram cookie.

You should be able to find a cookie with a ``session_id`` key. Copy it's value in the Instagram constructor as below : 
```python
from src import Instagram

def main():
    api = Instagram("THE_SESSION_ID")
    post = api.fetch_post_properties("CT-cnxGhvvO")
    # Outputs something of type types/posts/post_properties.json
    print(post)

if __name__ == "__main__":
    main()
```

Let me know if the ``session_id`` is great.

Another workaround is to connect to another network, such as 4G if you were on your homebox, or your homebox if you were on 4G. I thought it would be a great idea to implement proxies on this project, and I start thinking it urges.

**Comment by 89z** [comment]
Yes, I think anonymous access is no longer possible. But anonymous is possible, that is good.

**Comment by Quatrecentquatre-404** [comment]
Anonymous still available for some parts, but Instagram is working on reducing them as fast as possible, so this project is in danger.
